version: 2.1


jobs:
  build:
    working_directory: ~/yahooFinance-miniCLI

    docker:
      - image: circleci/python:3.6.4
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World! Construccion de Software'
            echo 'This is the delivery pipeline using Circle CI'
      - run:
          name: Install Pip Env
          command: |
            
            sudo pip install pipenv
            pipenv install

      
      - run:
          name: Installing dependencies
          command: 
            pwd
            pip install -r requirements.txt

      - run:
          name: Unit Testing Step
          command: |
            echo 'Unit Tests are about to run'


